import type {
  UserProfile,
  PatientProfile,
  Provider,
  Appointment,
  Alert,
  VitalsTimeSeries,
  VitalSign,
  Rule,
  Medication,
  LabResult,
  NursingNote,
  ImagingStudy,
  Encounter,
} from '@/types';

// Mock Users
export const mockUsers: UserProfile[] = [
  {
    userId: 'admin-001',
    name: 'System Administrator',
    email: 'admin@metro.health',
    roles: ['admin'],
    department: 'IT',
    avatar: 'https://api.dicebear.com/7.x/initials/svg?seed=SA',
  },
  {
    userId: 'cn-001',
    name: 'Sarah Williams',
    email: 'charge.nurse@metro.health',
    roles: ['charge_nurse', 'nurse'],
    unit: 'ICU',
    department: 'Critical Care',
    avatar: 'https://api.dicebear.com/7.x/initials/svg?seed=SW',
  },
  {
    userId: 'nurse-001',
    name: 'Jennifer Johnson',
    email: 'nurse.johnson@metro.health',
    roles: ['nurse'],
    unit: 'ICU',
    department: 'Critical Care',
    phone: '(555) 123-4567',
    avatar: 'https://api.dicebear.com/7.x/initials/svg?seed=JJ',
  },
  {
    userId: 'nurse-002',
    name: 'Michael Chen',
    email: 'nurse.chen@metro.health',
    roles: ['nurse'],
    unit: 'Medical-Surgical',
    department: 'General Medicine',
    phone: '(555) 234-5678',
    avatar: 'https://api.dicebear.com/7.x/initials/svg?seed=MC',
  },
  {
    userId: 'prov-001',
    name: 'Dr. Robert Smith',
    email: 'dr.smith@metro.health',
    roles: ['provider'],
    department: 'Internal Medicine',
    phone: '(555) 345-6789',
    avatar: 'https://api.dicebear.com/7.x/initials/svg?seed=RS',
  },
  {
    userId: 'prov-002',
    name: 'Dr. Emily Davis',
    email: 'dr.davis@metro.health',
    roles: ['provider'],
    department: 'Cardiology',
    phone: '(555) 456-7890',
    avatar: 'https://api.dicebear.com/7.x/initials/svg?seed=ED',
  },
  {
    userId: 'patient-001',
    name: 'John Anderson',
    email: 'patient1@metro.health',
    roles: ['patient'],
    patientId: 'P001',
    avatar: 'https://api.dicebear.com/7.x/initials/svg?seed=JA',
  },
  {
    userId: 'patient-002',
    name: 'Mary Thompson',
    email: 'patient2@metro.health',
    roles: ['patient'],
    patientId: 'P002',
    avatar: 'https://api.dicebear.com/7.x/initials/svg?seed=MT',
  },
];

// Mock Patients
export const mockPatients: PatientProfile[] = [
  {
    patientId: 'P001',
    firstName: 'John',
    lastName: 'Anderson',
    dateOfBirth: '1965-03-15',
    gender: 'male',
    mrn: 'MRN001234',
    bloodType: 'O+',
    allergies: ['Penicillin', 'Shellfish'],
    language: 'English',
    address: {
      street: '123 Main St',
      city: 'Springfield',
      state: 'IL',
      zipCode: '62701',
    },
    emergencyContact: {
      name: 'Jane Anderson',
      relationship: 'Spouse',
      phone: '(555) 111-2222',
    },
    careTeam: [
      { userId: 'prov-001', name: 'Dr. Robert Smith', role: 'provider', specialty: 'Internal Medicine', isPrimary: true },
      { userId: 'nurse-001', name: 'Jennifer Johnson', role: 'nurse', isPrimary: true },
    ],
    room: 'ICU-101',
    admissionDate: '2025-11-07T08:00:00Z',
    status: 'admitted',
    chiefComplaint: 'Chest pain and shortness of breath',
    diagnosis: ['Acute Coronary Syndrome', 'Hypertension'],
    riskLevel: 'high',
  },
  {
    patientId: 'P002',
    firstName: 'Mary',
    lastName: 'Thompson',
    dateOfBirth: '1978-07-22',
    gender: 'female',
    mrn: 'MRN001235',
    bloodType: 'A+',
    allergies: ['Latex'],
    language: 'English',
    address: {
      street: '456 Oak Ave',
      city: 'Springfield',
      state: 'IL',
      zipCode: '62702',
    },
    emergencyContact: {
      name: 'Robert Thompson',
      relationship: 'Husband',
      phone: '(555) 222-3333',
    },
    careTeam: [
      { userId: 'prov-002', name: 'Dr. Emily Davis', role: 'provider', specialty: 'Cardiology', isPrimary: true },
      { userId: 'nurse-001', name: 'Jennifer Johnson', role: 'nurse', isPrimary: true },
    ],
    room: 'ICU-102',
    admissionDate: '2025-11-08T14:30:00Z',
    status: 'admitted',
    chiefComplaint: 'Palpitations and dizziness',
    diagnosis: ['Atrial Fibrillation'],
    riskLevel: 'medium',
  },
  {
    patientId: 'P003',
    firstName: 'James',
    lastName: 'Wilson',
    dateOfBirth: '1952-11-30',
    gender: 'male',
    mrn: 'MRN001236',
    bloodType: 'B+',
    allergies: [],
    language: 'English',
    careTeam: [
      { userId: 'prov-001', name: 'Dr. Robert Smith', role: 'provider', specialty: 'Internal Medicine', isPrimary: true },
      { userId: 'nurse-002', name: 'Michael Chen', role: 'nurse', isPrimary: true },
    ],
    room: 'MS-201',
    admissionDate: '2025-11-06T10:00:00Z',
    status: 'admitted',
    chiefComplaint: 'Pneumonia',
    diagnosis: ['Community-Acquired Pneumonia', 'COPD'],
    riskLevel: 'medium',
  },
  {
    patientId: 'P004',
    firstName: 'Patricia',
    lastName: 'Martinez',
    dateOfBirth: '1990-05-18',
    gender: 'female',
    mrn: 'MRN001237',
    bloodType: 'AB-',
    allergies: ['Sulfa drugs'],
    language: 'Spanish',
    careTeam: [
      { userId: 'prov-002', name: 'Dr. Emily Davis', role: 'provider', specialty: 'Cardiology', isPrimary: true },
      { userId: 'nurse-002', name: 'Michael Chen', role: 'nurse', isPrimary: true },
    ],
    room: 'MS-202',
    admissionDate: '2025-11-09T09:15:00Z',
    status: 'admitted',
    chiefComplaint: 'Post-surgical recovery',
    diagnosis: ['Post-operative monitoring'],
    riskLevel: 'low',
  },
  {
    patientId: 'P005',
    firstName: 'Robert',
    lastName: 'Garcia',
    dateOfBirth: '1945-02-10',
    gender: 'male',
    mrn: 'MRN001238',
    bloodType: 'O-',
    allergies: ['Aspirin'],
    language: 'English',
    careTeam: [
      { userId: 'prov-001', name: 'Dr. Robert Smith', role: 'provider', specialty: 'Internal Medicine', isPrimary: true },
      { userId: 'nurse-001', name: 'Jennifer Johnson', role: 'nurse', isPrimary: true },
    ],
    room: 'ICU-103',
    admissionDate: '2025-11-05T16:45:00Z',
    status: 'admitted',
    chiefComplaint: 'Sepsis',
    diagnosis: ['Septic Shock', 'Acute Kidney Injury'],
    riskLevel: 'critical',
  },
];

// Mock Providers
export const mockProviders: Provider[] = [
  {
    userId: 'prov-001',
    name: 'Dr. Robert Smith',
    email: 'dr.smith@metro.health',
    specialty: 'Internal Medicine',
    department: 'Internal Medicine',
    npiNumber: 'NPI1234567890',
    phone: '(555) 345-6789',
    availability: [
      { dayOfWeek: 1, startTime: '08:00', endTime: '17:00' },
      { dayOfWeek: 2, startTime: '08:00', endTime: '17:00' },
      { dayOfWeek: 3, startTime: '08:00', endTime: '17:00' },
      { dayOfWeek: 4, startTime: '08:00', endTime: '17:00' },
      { dayOfWeek: 5, startTime: '08:00', endTime: '12:00' },
    ],
  },
  {
    userId: 'prov-002',
    name: 'Dr. Emily Davis',
    email: 'dr.davis@metro.health',
    specialty: 'Cardiology',
    department: 'Cardiology',
    npiNumber: 'NPI0987654321',
    phone: '(555) 456-7890',
    availability: [
      { dayOfWeek: 1, startTime: '09:00', endTime: '18:00' },
      { dayOfWeek: 2, startTime: '09:00', endTime: '18:00' },
      { dayOfWeek: 3, startTime: '09:00', endTime: '18:00' },
      { dayOfWeek: 4, startTime: '09:00', endTime: '18:00' },
    ],
  },
];

// Generate realistic vitals time series
function generateVitalsTimeSeries(patientId: string, hours: number = 24): VitalsTimeSeries {
  const readings: VitalSign[] = [];
  const now = new Date();
  
  for (let i = hours; i >= 0; i--) {
    const timestamp = new Date(now.getTime() - i * 60 * 60 * 1000).toISOString();
    
    // Add some realistic variation based on patient risk
    const patient = mockPatients.find(p => p.patientId === patientId);
    const isHighRisk = patient?.riskLevel === 'high' || patient?.riskLevel === 'critical';
    
    readings.push({
      timestamp,
      heartRate: isHighRisk ? 95 + Math.random() * 30 : 70 + Math.random() * 20,
      systolicBP: isHighRisk ? 140 + Math.random() * 40 : 120 + Math.random() * 20,
      diastolicBP: isHighRisk ? 85 + Math.random() * 20 : 75 + Math.random() * 15,
      respiratoryRate: isHighRisk ? 20 + Math.random() * 8 : 14 + Math.random() * 6,
      temperature: 36.5 + Math.random() * 1.5,
      spO2: isHighRisk ? 88 + Math.random() * 8 : 95 + Math.random() * 4,
      painLevel: Math.floor(Math.random() * (isHighRisk ? 7 : 4)),
      consciousness: 'alert',
    });
  }
  
  return { patientId, readings };
}

export const mockVitals: VitalsTimeSeries[] = mockPatients.map(p => 
  generateVitalsTimeSeries(p.patientId)
);

// Mock Appointments
export const mockAppointments: Appointment[] = [
  {
    appointmentId: 'APT001',
    patientId: 'P001',
    providerId: 'prov-001',
    dateTime: '2025-11-10T09:00:00Z',
    duration: 30,
    type: 'follow-up',
    status: 'scheduled',
    reason: 'Post-discharge follow-up',
    location: 'Cardiology Clinic',
    room: 'Exam Room 1',
  },
  {
    appointmentId: 'APT002',
    patientId: 'P002',
    providerId: 'prov-002',
    dateTime: '2025-11-09T14:00:00Z',
    duration: 45,
    type: 'consultation',
    status: 'checked-in',
    reason: 'Cardiac consultation',
    checkInTime: '2025-11-09T13:55:00Z',
    location: 'Cardiology Clinic',
    room: 'Exam Room 2',
  },
  {
    appointmentId: 'APT003',
    patientId: 'P003',
    providerId: 'prov-001',
    dateTime: '2025-11-09T10:30:00Z',
    duration: 30,
    type: 'routine',
    status: 'completed',
    reason: 'Routine check-up',
    checkInTime: '2025-11-09T10:25:00Z',
    location: 'Internal Medicine',
  },
];

// Mock Alerts
export const mockAlerts: Alert[] = [
  {
    alertId: 'ALT001',
    patientId: 'P005',
    type: 'vitals',
    severity: 'critical',
    title: 'Critical Vital Signs',
    message: 'Patient heart rate 125 bpm, SpO2 87% - SIRS criteria met',
    timestamp: new Date(Date.now() - 15 * 60 * 1000).toISOString(),
    source: 'SIRS Rule',
  },
  {
    alertId: 'ALT002',
    patientId: 'P001',
    type: 'vitals',
    severity: 'high',
    title: 'Elevated Blood Pressure',
    message: 'Systolic BP 165 mmHg exceeds threshold',
    timestamp: new Date(Date.now() - 45 * 60 * 1000).toISOString(),
    acknowledgedBy: 'nurse-001',
    acknowledgedAt: new Date(Date.now() - 30 * 60 * 1000).toISOString(),
    source: 'EWS Criteria',
  },
  {
    alertId: 'ALT003',
    patientId: 'P002',
    type: 'medication',
    severity: 'medium',
    title: 'Medication Due',
    message: 'Metoprolol 25mg due at 14:00',
    timestamp: new Date(Date.now() - 2 * 60 * 60 * 1000).toISOString(),
    resolvedBy: 'nurse-001',
    resolvedAt: new Date(Date.now() - 90 * 60 * 1000).toISOString(),
  },
  {
    alertId: 'ALT004',
    patientId: 'P003',
    type: 'lab',
    severity: 'medium',
    title: 'Abnormal Lab Result',
    message: 'WBC count 12,500 - elevated',
    timestamp: new Date(Date.now() - 3 * 60 * 60 * 1000).toISOString(),
  },
];

// Mock Clinical Rules
export const mockRules: Rule[] = [
  {
    ruleId: 'RULE001',
    name: 'SIRS Criteria',
    description: 'Systemic Inflammatory Response Syndrome detection',
    type: 'SIRS',
    criteria: [
      { parameter: 'temperature', operator: '>', value: 38 },
      { parameter: 'heartRate', operator: '>', value: 90 },
      { parameter: 'respiratoryRate', operator: '>', value: 20 },
    ],
    severity: 'critical',
    enabled: true,
    createdBy: 'admin-001',
    createdAt: '2025-01-01T00:00:00Z',
  },
  {
    ruleId: 'RULE002',
    name: 'Early Warning Score',
    description: 'Modified Early Warning Score for patient deterioration',
    type: 'EWS',
    criteria: [
      { parameter: 'systolicBP', operator: '<', value: 90 },
      { parameter: 'heartRate', operator: '>', value: 110 },
      { parameter: 'spO2', operator: '<', value: 92 },
    ],
    severity: 'high',
    enabled: true,
    createdBy: 'admin-001',
    createdAt: '2025-01-01T00:00:00Z',
  },
];

// Mock Medications
export const mockMedications: Medication[] = [
  {
    medicationId: 'MED001',
    patientId: 'P001',
    name: 'Aspirin',
    dosage: '81mg',
    frequency: 'Once daily',
    route: 'oral',
    startDate: '2025-11-07',
    prescribedBy: 'prov-001',
    status: 'active',
    instructions: 'Take with food',
  },
  {
    medicationId: 'MED002',
    patientId: 'P002',
    name: 'Metoprolol',
    dosage: '25mg',
    frequency: 'Twice daily',
    route: 'oral',
    startDate: '2025-11-08',
    prescribedBy: 'prov-002',
    status: 'active',
  },
];

// Mock Nursing Notes
export const mockNursingNotes: NursingNote[] = [
  {
    noteId: 'NOTE001',
    patientId: 'P001',
    authorId: 'nurse-001',
    authorName: 'Jennifer Johnson',
    timestamp: new Date(Date.now() - 2 * 60 * 60 * 1000).toISOString(),
    category: 'assessment',
    content: 'Patient alert and oriented x3. Reports chest pain 3/10. Vitals stable.',
  },
  {
    noteId: 'NOTE002',
    patientId: 'P001',
    authorId: 'nurse-001',
    authorName: 'Jennifer Johnson',
    timestamp: new Date(Date.now() - 4 * 60 * 60 * 1000).toISOString(),
    category: 'intervention',
    content: 'Administered nitroglycerin 0.4mg SL for chest pain. Pain reduced to 1/10.',
  },
];

// Mock Lab Results
export const mockLabResults: LabResult[] = [
  {
    labId: 'LAB001',
    patientId: 'P001',
    testName: 'Complete Blood Count (CBC)',
    value: '12,500',
    unit: 'cells/µL',
    referenceRange: '4,500-11,000',
    status: 'completed',
    orderedBy: 'prov-001',
    orderedDate: '2025-11-08T08:00:00Z',
    resultDate: '2025-11-08T14:30:00Z',
    abnormalFlag: 'high',
  },
  {
    labId: 'LAB002',
    patientId: 'P001',
    testName: 'Troponin I',
    value: '0.8',
    unit: 'ng/mL',
    referenceRange: '<0.04',
    status: 'completed',
    orderedBy: 'prov-001',
    orderedDate: '2025-11-07T10:00:00Z',
    resultDate: '2025-11-07T12:15:00Z',
    abnormalFlag: 'critical',
    notes: 'Elevated - consistent with cardiac injury',
  },
  {
    labId: 'LAB003',
    patientId: 'P001',
    testName: 'BNP',
    value: '450',
    unit: 'pg/mL',
    referenceRange: '<100',
    status: 'completed',
    orderedBy: 'prov-001',
    orderedDate: '2025-11-07T10:00:00Z',
    resultDate: '2025-11-07T13:00:00Z',
    abnormalFlag: 'high',
  },
  {
    labId: 'LAB004',
    patientId: 'P002',
    testName: 'Hemoglobin A1C',
    value: '6.2',
    unit: '%',
    referenceRange: '4.0-5.6',
    status: 'completed',
    orderedBy: 'prov-002',
    orderedDate: '2025-11-08T09:00:00Z',
    resultDate: '2025-11-09T08:00:00Z',
    abnormalFlag: 'high',
  },
  {
    labId: 'LAB005',
    patientId: 'P003',
    testName: 'Chest X-Ray',
    value: 'Bilateral infiltrates',
    unit: 'Impression',
    referenceRange: 'Clear lung fields',
    status: 'completed',
    orderedBy: 'prov-001',
    orderedDate: '2025-11-06T11:00:00Z',
    resultDate: '2025-11-06T15:00:00Z',
    notes: 'Consistent with pneumonia',
  },
];

// Mock Imaging Studies
export const mockImagingStudies: ImagingStudy[] = [
  {
    studyId: 'IMG001',
    patientId: 'P001',
    type: 'ct',
    bodyPart: 'Chest',
    description: 'CT Angiography - Chest',
    orderedBy: 'prov-001',
    orderedDate: '2025-11-07T09:00:00Z',
    performedDate: '2025-11-07T11:30:00Z',
    status: 'completed',
    findings: 'No evidence of pulmonary embolism. Mild coronary artery calcification.',
    radiologist: 'Dr. Sarah Miller',
    urgency: 'stat',
  },
  {
    studyId: 'IMG002',
    patientId: 'P001',
    type: 'x-ray',
    bodyPart: 'Chest',
    description: 'Chest X-Ray PA and Lateral',
    orderedBy: 'prov-001',
    orderedDate: '2025-11-07T08:00:00Z',
    performedDate: '2025-11-07T08:45:00Z',
    status: 'completed',
    findings: 'Mild cardiomegaly. No acute infiltrates. No pleural effusion.',
    radiologist: 'Dr. Michael Wong',
    urgency: 'urgent',
  },
  {
    studyId: 'IMG003',
    patientId: 'P002',
    type: 'ultrasound',
    bodyPart: 'Heart',
    description: 'Echocardiogram - Transthoracic',
    orderedBy: 'prov-002',
    orderedDate: '2025-11-08T10:00:00Z',
    performedDate: '2025-11-08T14:00:00Z',
    status: 'completed',
    findings: 'Normal LV systolic function. EF 55-60%. Mild mitral regurgitation.',
    radiologist: 'Dr. Patricia Lee',
    urgency: 'routine',
  },
  {
    studyId: 'IMG004',
    patientId: 'P003',
    type: 'x-ray',
    bodyPart: 'Chest',
    description: 'Portable Chest X-Ray',
    orderedBy: 'prov-001',
    orderedDate: '2025-11-06T10:00:00Z',
    performedDate: '2025-11-06T10:30:00Z',
    status: 'completed',
    findings: 'Bilateral lower lobe infiltrates consistent with pneumonia. Small left pleural effusion.',
    radiologist: 'Dr. Michael Wong',
    urgency: 'urgent',
  },
  {
    studyId: 'IMG005',
    patientId: 'P005',
    type: 'ct',
    bodyPart: 'Abdomen/Pelvis',
    description: 'CT Abdomen and Pelvis with Contrast',
    orderedBy: 'prov-001',
    orderedDate: '2025-11-05T17:00:00Z',
    performedDate: '2025-11-05T19:00:00Z',
    status: 'completed',
    findings: 'Enlarged kidneys with multiple renal cysts. No hydronephrosis. Mild ascites.',
    radiologist: 'Dr. Sarah Miller',
    urgency: 'urgent',
  },
];

// Mock Encounters
export const mockEncounters: Encounter[] = [
  {
    encounterId: 'ENC001',
    patientId: 'P001',
    type: 'inpatient',
    status: 'in-progress',
    startDate: '2025-11-07T08:00:00Z',
    providerId: 'prov-001',
    department: 'Cardiology',
    chiefComplaint: 'Chest pain and shortness of breath',
    diagnosis: ['Acute Coronary Syndrome', 'Hypertension'],
    procedures: ['Cardiac catheterization', 'Stent placement'],
    notes: 'Patient admitted with acute chest pain. Troponin elevated. Underwent cardiac cath with stent to LAD.',
  },
  {
    encounterId: 'ENC002',
    patientId: 'P002',
    type: 'inpatient',
    status: 'in-progress',
    startDate: '2025-11-08T14:30:00Z',
    providerId: 'prov-002',
    department: 'Cardiology',
    chiefComplaint: 'Palpitations and dizziness',
    diagnosis: ['Atrial Fibrillation'],
    procedures: ['Cardioversion (scheduled)'],
    notes: 'New onset atrial fibrillation. Rate controlled with metoprolol. Scheduled for cardioversion.',
  },
  {
    encounterId: 'ENC003',
    patientId: 'P001',
    type: 'emergency',
    status: 'finished',
    startDate: '2025-11-07T06:30:00Z',
    endDate: '2025-11-07T08:00:00Z',
    providerId: 'prov-001',
    department: 'Emergency Department',
    chiefComplaint: 'Chest pain',
    diagnosis: ['Rule out MI'],
    procedures: ['EKG', 'Troponin', 'Chest X-Ray'],
    notes: 'Patient presented with chest pain. EKG showed ST elevation. Transferred to CCU.',
  },
  {
    encounterId: 'ENC004',
    patientId: 'P003',
    type: 'inpatient',
    status: 'in-progress',
    startDate: '2025-11-06T10:00:00Z',
    providerId: 'prov-001',
    department: 'Internal Medicine',
    chiefComplaint: 'Cough, fever, shortness of breath',
    diagnosis: ['Community-Acquired Pneumonia', 'COPD exacerbation'],
    procedures: ['Chest X-Ray', 'Blood cultures', 'Sputum culture'],
    notes: 'Admitted with pneumonia. Started on IV antibiotics. Oxygen requirement improving.',
  },
  {
    encounterId: 'ENC005',
    patientId: 'P005',
    type: 'emergency',
    status: 'finished',
    startDate: '2025-11-05T15:00:00Z',
    endDate: '2025-11-05T16:45:00Z',
    providerId: 'prov-001',
    department: 'Emergency Department',
    chiefComplaint: 'Altered mental status, fever',
    diagnosis: ['Sepsis, source unclear'],
    procedures: ['Blood cultures', 'Urinalysis', 'Chest X-Ray', 'CT abdomen/pelvis'],
    notes: 'Presented with sepsis. Hemodynamically unstable. Admitted to ICU.',
  },
];

// Authentication credentials (for demo purposes)
export const mockCredentials = {
  // Original credentials
  'admin@metro.health': { password: 'password123', userId: 'admin-001' },
  'charge.nurse@metro.health': { password: 'password123', userId: 'cn-001' },
  'nurse.johnson@metro.health': { password: 'password123', userId: 'nurse-001' },
  'nurse.chen@metro.health': { password: 'password123', userId: 'nurse-002' },
  'dr.smith@metro.health': { password: 'password123', userId: 'prov-001' },
  'dr.davis@metro.health': { password: 'password123', userId: 'prov-002' },
  'patient1@metro.health': { password: 'password123', userId: 'patient-001' },
  'patient2@metro.health': { password: 'password123', userId: 'patient-002' },
  // Simplified aliases for easier login
  'admin@metrohealth.org': { password: 'password123', userId: 'admin-001' },
  'nurse@metrohealth.org': { password: 'password123', userId: 'nurse-001' },
  'physician@metrohealth.org': { password: 'password123', userId: 'prov-001' },
  'patient@metrohealth.org': { password: 'password123', userId: 'patient-001' },
};
